2022-05-18 16:39:01,300 INFO  [main] SpringbootApplication: Starting SpringbootApplication using Java 1.8.0_131 on DESKTOP-UCTQGUL with PID 3172 (G:\springboot-demo\target\classes started by CCH in G:\springboot-demo)
2022-05-18 16:39:01,313 INFO  [main] SpringbootApplication: The following profiles are active: test
2022-05-18 16:39:01,339 INFO  [background-preinit] Version: HV000001: Hibernate Validator 6.0.13.Final
2022-05-18 16:39:09,324 INFO  [main] TomcatWebServer: Tomcat initialized with port(s): 8082 (http)
2022-05-18 16:39:09,365 INFO  [main] Http11NioProtocol: Initializing ProtocolHandler ["http-nio-8082"]
2022-05-18 16:39:09,366 INFO  [main] StandardService: Starting service [Tomcat]
2022-05-18 16:39:09,367 INFO  [main] StandardEngine: Starting Servlet engine: [Apache Tomcat/9.0.54]
2022-05-18 16:39:09,383 INFO  [main] AprLifecycleListener: An older version [1.2.25] of the Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.30]
2022-05-18 16:39:09,393 INFO  [main] AprLifecycleListener: Loaded Apache Tomcat Native library [1.2.25] using APR version [1.7.0].
2022-05-18 16:39:09,394 INFO  [main] AprLifecycleListener: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [false].
2022-05-18 16:39:09,394 INFO  [main] AprLifecycleListener: APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2022-05-18 16:39:09,511 INFO  [main] AprLifecycleListener: OpenSSL successfully initialized [OpenSSL 1.1.1g  21 Apr 2020]
2022-05-18 16:39:09,979 INFO  [main] [/]: Initializing Spring embedded WebApplicationContext
2022-05-18 16:39:09,979 INFO  [main] ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 8399 ms
2022-05-18 16:39:12,713 INFO  [main] PropertySourcedRequestMappingHandlerMapping: Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-05-18 16:39:13,772 INFO  [main] Http11NioProtocol: Starting ProtocolHandler ["http-nio-8082"]
2022-05-18 16:39:13,813 INFO  [main] TomcatWebServer: Tomcat started on port(s): 8082 (http) with context path ''
2022-05-18 16:39:13,815 INFO  [main] DocumentationPluginsBootstrapper: Context refreshed
2022-05-18 16:39:13,881 INFO  [main] DocumentationPluginsBootstrapper: Found 1 custom documentation plugin(s)
2022-05-18 16:39:13,937 INFO  [main] ApiListingReferenceScanner: Scanning for api listing references
2022-05-18 16:39:14,502 INFO  [main] SpringbootApplication: Started SpringbootApplication in 16.76 seconds (JVM running for 19.917)
2022-05-18 16:39:20,014 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:39:21,433 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:39:21,434 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:39:21,453 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:39:21,453 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:39:21,471 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:39:21,471 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:39:21,512 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:39:40,017 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:39:40,044 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:39:40,044 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:39:40,062 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:39:40,062 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:39:40,081 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:39:40,081 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:39:40,101 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:42:12,943 INFO  [background-preinit] Version: HV000001: Hibernate Validator 6.0.13.Final
2022-05-18 16:42:12,972 INFO  [main] SpringbootApplication: Starting SpringbootApplication using Java 1.8.0_131 on DESKTOP-UCTQGUL with PID 16224 (G:\springboot-demo\target\classes started by CCH in G:\springboot-demo)
2022-05-18 16:42:12,972 INFO  [main] SpringbootApplication: The following profiles are active: test
2022-05-18 16:42:28,714 INFO  [background-preinit] Version: HV000001: Hibernate Validator 6.0.13.Final
2022-05-18 16:42:28,738 INFO  [main] SpringbootApplication: Starting SpringbootApplication using Java 1.8.0_131 on DESKTOP-UCTQGUL with PID 7644 (G:\springboot-demo\target\classes started by CCH in G:\springboot-demo)
2022-05-18 16:42:28,739 INFO  [main] SpringbootApplication: The following profiles are active: test
2022-05-18 16:42:31,913 INFO  [main] TomcatWebServer: Tomcat initialized with port(s): 8082 (http)
2022-05-18 16:42:32,012 INFO  [main] Http11NioProtocol: Initializing ProtocolHandler ["http-nio-8082"]
2022-05-18 16:42:32,012 INFO  [main] StandardService: Starting service [Tomcat]
2022-05-18 16:42:32,012 INFO  [main] StandardEngine: Starting Servlet engine: [Apache Tomcat/9.0.54]
2022-05-18 16:42:32,015 INFO  [main] AprLifecycleListener: An older version [1.2.25] of the Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.30]
2022-05-18 16:42:32,015 INFO  [main] AprLifecycleListener: Loaded Apache Tomcat Native library [1.2.25] using APR version [1.7.0].
2022-05-18 16:42:32,016 INFO  [main] AprLifecycleListener: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [false].
2022-05-18 16:42:32,016 INFO  [main] AprLifecycleListener: APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2022-05-18 16:42:32,018 INFO  [main] AprLifecycleListener: OpenSSL successfully initialized [OpenSSL 1.1.1g  21 Apr 2020]
2022-05-18 16:42:32,241 INFO  [main] [/]: Initializing Spring embedded WebApplicationContext
2022-05-18 16:42:32,241 INFO  [main] ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 3404 ms
2022-05-18 16:44:14,917 INFO  [main] PropertySourcedRequestMappingHandlerMapping: Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2022-05-18 16:44:56,876 INFO  [main] Http11NioProtocol: Starting ProtocolHandler ["http-nio-8082"]
2022-05-18 16:44:57,251 INFO  [main] TomcatWebServer: Tomcat started on port(s): 8082 (http) with context path ''
2022-05-18 16:44:57,314 INFO  [main] DocumentationPluginsBootstrapper: Context refreshed
2022-05-18 16:44:58,251 INFO  [main] DocumentationPluginsBootstrapper: Found 1 custom documentation plugin(s)
2022-05-18 16:44:59,563 INFO  [main] ApiListingReferenceScanner: Scanning for api listing references
2022-05-18 16:45:18,623 INFO  [main] SpringbootApplication: Started SpringbootApplication in 171.342 seconds (JVM running for 174.744)
2022-05-18 16:45:20,015 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:45:32,030 INFO  [http-nio-8082-exec-2] [/]: Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-05-18 16:45:32,050 INFO  [http-nio-8082-exec-2] DispatcherServlet: Initializing Servlet 'dispatcherServlet'
2022-05-18 16:45:33,201 INFO  [http-nio-8082-exec-2] DispatcherServlet: Completed initialization in 1132 ms
2022-05-18 16:46:33,075 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:46:33,091 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:46:33,153 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:46:33,169 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:46:33,216 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:46:33,232 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:46:33,388 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:46:33,450 INFO  [scheduling-1] ScheduledTask: ==========开始每日导入Tranlog流水表=========
2022-05-18 16:46:33,935 INFO  [scheduling-1] HikariDataSource: HikariPool-1 - Starting...
2022-05-18 16:46:52,359 INFO  [scheduling-1] PoolBase: HikariPool-1 - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)
2022-05-18 16:46:52,421 INFO  [scheduling-1] HikariDataSource: HikariPool-1 - Start completed.
2022-05-18 16:47:44,286 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=51s751ms297µs500ns).
2022-05-18 16:47:44,660 ERROR [scheduling-1] ScheduledTask: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy83.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy88.insertTranlog(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy89.insertTranlog(Unknown Source)
	at com.cch.demo.account.scheduled.ScheduledTask.insertIntoTranlog(ScheduledTask.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy132.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 32 common frames omitted
2022-05-18 16:47:44,660 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 16:47:44,738 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}]
2022-05-18 16:47:44,738 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 16:47:44,769 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:47:44,800 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:47:44,800 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:47:44,816 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:47:44,816 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:47:44,832 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:47:44,832 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:47:44,847 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:48:00,006 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:48:00,022 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:00,022 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:00,037 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:00,037 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:00,053 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:00,053 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:00,053 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:48:00,053 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 16:48:00,053 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}]
2022-05-18 16:48:00,053 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 16:48:00,053 INFO  [scheduling-1] ScheduledTask: ==========开始每日导入Tranlog流水表=========
2022-05-18 16:48:00,053 ERROR [scheduling-1] ScheduledTask: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy83.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy88.insertTranlog(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy89.insertTranlog(Unknown Source)
	at com.cch.demo.account.scheduled.ScheduledTask.insertIntoTranlog(ScheduledTask.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy132.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 32 common frames omitted
2022-05-18 16:48:20,014 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:48:20,374 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:20,389 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:20,436 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:20,451 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:20,498 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:20,514 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:20,608 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:48:40,010 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:48:40,395 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:40,412 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:40,471 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:40,489 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:40,560 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:48:40,574 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:48:40,677 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:50:36,877 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:50:36,877 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m52s554ms41µs600ns).
2022-05-18 16:50:36,877 INFO  [http-nio-8082-exec-2] BillingController: ==========接到住建局应收单据接口请求=========
2022-05-18 16:50:49,819 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:50:49,819 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:50:49,850 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:50:49,850 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:50:49,866 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:50:49,866 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:50:49,881 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:50:49,881 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 16:50:49,881 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}]
2022-05-18 16:50:49,881 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 16:50:49,881 INFO  [scheduling-1] ScheduledTask: ==========开始每日导入Tranlog流水表=========
2022-05-18 16:52:16,245 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m8s805ms397µs600ns).
2022-05-18 16:52:34,861 ERROR [scheduling-1] ScheduledTask: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy83.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy88.insertTranlog(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy89.insertTranlog(Unknown Source)
	at com.cch.demo.account.scheduled.ScheduledTask.insertIntoTranlog(ScheduledTask.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy132.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 32 common frames omitted
2022-05-18 16:52:34,877 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:52:34,892 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:52:34,892 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:52:34,908 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:52:34,908 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:52:34,908 INFO  [http-nio-8082-exec-2] GlobalFillMetaObjectHandler: start insert fill...
2022-05-18 16:52:34,923 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:52:34,923 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:52:34,923 INFO  [http-nio-8082-exec-2] BillingController: 合同号：string应收单据插库成功
2022-05-18 16:52:34,939 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:52:34,939 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 16:52:34,939 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}, {EID=string, PAYMENTAMOUNT=0, BNO=string, CNO=string, PAYENDTIME=string, BID=string, CREATETIME=2022-05-18 16:52:34.0, TYPE=0, PAYSTARTTIME=string, CID=string}]
2022-05-18 16:52:34,939 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 16:52:34,939 INFO  [scheduling-1] ScheduledTask: 第1条应收单据核账开始,合同备案号：string,支付金额：0,账单号：string
2022-05-18 16:52:38,597 INFO  [http-nio-8082-exec-6] BillingController: ==========接到住建局应收单据接口请求=========
2022-05-18 16:52:38,601 INFO  [http-nio-8082-exec-6] BillingController: 合同号：string应收单据库里已存在
2022-05-18 16:52:38,601 INFO  [http-nio-8082-exec-6] BillingController: 接到住建局应收单据接口请求,返回操作成功
2022-05-18 16:52:40,013 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:52:40,028 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:52:40,028 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:52:40,043 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:52:40,043 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:52:40,064 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:52:40,064 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:52:40,081 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:53:43,805 INFO  [scheduling-1] ScheduledTask: ==========开始每日导入Tranlog流水表=========
2022-05-18 16:53:43,805 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=57s552ms547µs700ns).
2022-05-18 16:53:43,805 INFO  [http-nio-8082-exec-4] BillingController: ==========接到住建局应收单据接口请求=========
2022-05-18 16:54:52,650 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m8s851ms100µs600ns).
2022-05-18 16:55:36,608 ERROR [scheduling-1] ScheduledTask: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve com.cch.demo.account.mapper.TranlogMapper.insertTranlog
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve com.cch.demo.account.mapper.TranlogMapper.insertTranlog
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy83.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy88.insertTranlog(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy89.insertTranlog(Unknown Source)
	at com.cch.demo.account.scheduled.ScheduledTask.insertIntoTranlog(ScheduledTask.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve com.cch.demo.account.mapper.TranlogMapper.insertTranlog
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 32 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:93)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:53)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	... 38 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 112806ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 46 common frames omitted
2022-05-18 16:55:36,608 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:55:36,624 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:55:36,624 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:55:38,905 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:55:38,905 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=46s257ms987µs700ns).
2022-05-18 16:55:46,173 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:55:46,173 INFO  [http-nio-8082-exec-4] BillingController: 合同号：string应收单据库里已存在
2022-05-18 16:55:47,142 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:55:47,142 INFO  [http-nio-8082-exec-4] BillingController: 接到住建局应收单据接口请求,返回操作成功
2022-05-18 16:55:47,142 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:55:47,672 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:55:47,672 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 16:55:52,092 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}, {EID=string, PAYMENTAMOUNT=0, BNO=string, CNO=string, PAYENDTIME=string, BID=string, CREATETIME=2022-05-18 16:52:34.0, TYPE=0, PAYSTARTTIME=string, CID=string}]
2022-05-18 16:55:52,092 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 16:55:52,107 INFO  [scheduling-1] ScheduledTask: 第1条应收单据核账开始,合同备案号：string,支付金额：0,账单号：string
2022-05-18 16:56:00,605 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 16:56:00,605 INFO  [http-nio-8082-exec-8] BillingController: ==========接到住建局应收单据接口请求=========
2022-05-18 16:56:02,370 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}, {EID=string, PAYMENTAMOUNT=0, BNO=string, CNO=string, PAYENDTIME=string, BID=string, CREATETIME=2022-05-18 16:52:34.0, TYPE=0, PAYSTARTTIME=string, CID=string}]
2022-05-18 16:56:02,370 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 16:56:02,370 INFO  [scheduling-1] ScheduledTask: 第1条应收单据核账开始,合同备案号：string,支付金额：0,账单号：string
2022-05-18 16:56:02,370 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 16:56:03,089 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:56:03,089 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:56:04,151 INFO  [http-nio-8082-exec-8] BillingController: 合同号：string应收单据库里已存在
2022-05-18 16:56:04,151 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:56:04,151 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:56:06,291 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 16:56:06,291 INFO  [http-nio-8082-exec-8] BillingController: 接到住建局应收单据接口请求,返回操作成功
2022-05-18 16:56:06,291 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 16:56:18,122 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 16:56:18,122 INFO  [scheduling-1] ScheduledTask: ==========开始每日导入Tranlog流水表=========
2022-05-18 16:56:28,279 ERROR [scheduling-1] ScheduledTask: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy83.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy88.insertTranlog(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy89.insertTranlog(Unknown Source)
	at com.cch.demo.account.scheduled.ScheduledTask.insertIntoTranlog(ScheduledTask.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy132.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 32 common frames omitted
2022-05-18 16:56:34,982 INFO  [scheduling-1] ScheduledTask: ==========发送请求给住建局,开始取token=========
2022-05-18 17:03:35,761 WARN  [HikariPool-1 housekeeper] HikariPool: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=6m45s866ms130µs600ns).
2022-05-18 17:18:34,966 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 17:18:34,966 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 17:18:34,966 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 17:18:34,966 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 17:18:34,966 INFO  [scheduling-1] RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://22.36.12.109:20089: No route to host: connect
2022-05-18 17:18:34,966 INFO  [scheduling-1] RetryExec: Retrying request to {}->http://22.36.12.109:20089
2022-05-18 17:18:34,966 ERROR [scheduling-1] ScheduledTask: null
java.lang.NullPointerException: null
	at com.cch.demo.account.util.HttpClientUtil.post(HttpClientUtil.java:99)
	at com.cch.demo.account.scheduled.ScheduledTask.getToken(ScheduledTask.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-05-18 17:18:34,966 INFO  [scheduling-1] ScheduledTask: ==========开始每日导入Tranlog流水表=========
2022-05-18 17:18:34,966 ERROR [scheduling-1] ScheduledTask: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### The error may exist in file [G:\springboot-demo\target\classes\mapper\TranlogMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: insert into Tranlog("ACCOUNTNUMBER", "CONTRACT","PAYTIME", "PAYAMOUNT", "SERIALNUMBER")         select "主账号","附言","交易日期","交易金额","交易流水号" from M_CTISG_VIEW t         where             to_date(t."交易日期",'yyyyMMdd') between                 (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)                 and (to_date(to_char(sysdate,'yyyyMMdd'),'yyyyMMdd') - interval'4' day)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy83.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy88.insertTranlog(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy89.insertTranlog(Unknown Source)
	at com.cch.demo.account.scheduled.ScheduledTask.insertIntoTranlog(ScheduledTask.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy132.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 32 common frames omitted
2022-05-18 17:18:34,966 INFO  [scheduling-1] ScheduledTask: ==========入金核账开始=========
2022-05-18 17:18:34,981 INFO  [scheduling-1] ScheduledTask: Billing应收单据表核账失败的记录：[{EID=qiye1, PAYMENTAMOUNT=3000, SPECIALACCOUNTNO=621081060001, CNO=2021254321100, PAYENDTIME=20211101, BID=bill3, CREATETIME=2021-11-09 13:34:28.0, TYPE=0, CID=202154321004}, {EID=string, PAYMENTAMOUNT=0, BNO=string, CNO=string, PAYENDTIME=string, BID=string, CREATETIME=2022-05-18 16:52:34.0, TYPE=0, PAYSTARTTIME=string, CID=string}]
2022-05-18 17:18:34,981 INFO  [scheduling-1] ScheduledTask: 第0条应收单据核账开始,合同备案号：2021254321100,支付金额：3000,账单号：bill3
2022-05-18 17:18:34,981 INFO  [scheduling-1] ScheduledTask: 第1条应收单据核账开始,合同备案号：string,支付金额：0,账单号：string
2022-05-18 17:18:35,231 INFO  [SpringApplicationShutdownHook] HikariDataSource: HikariPool-1 - Shutdown initiated...
2022-05-18 17:18:35,247 INFO  [SpringApplicationShutdownHook] HikariDataSource: HikariPool-1 - Shutdown completed.
